complete -f -c wleave
complete -c wleave -s h -l help -d "Show help message and stop"
complete -c wleave -s v -l version -d "Show version number and stop"
complete -c wleave -s l -l layout -r -d "Specify a layout file"
complete -c wleave -s C -l css -r -d "Specify a css file"
complete -c wleave -s b -l buttons-per-row -r -d "Set the number of buttons per row"
complete -c wleave -s m -l margin -r -d "Set margin around buttons"
complete -c wleave -s L -l margin-left -r -d "Set margin for left of buttons"
complete -c wleave -s R -l margin-right -r -d "Set margin for right of buttons"
complete -c wleave -s T -l margin-top -r -d "Set margin for top of buttons"
complete -c wleave -s B -l margin-bottom -r -d "Set margin for bottom of buttons"
complete -c wleave -s r -l row-spacing -r -d "Set space between buttons rows"
complete -c wleave -s c -l column-spacing -r -d "Set space between buttons columns"
complete -c wleave -s p -l protocol -r -d "Use layer-shell or xdg protocol"
